### ISSUE TITLE
Break out helpers into individual exports

### ISSUE THREAD

**Issue by clarle** [yahoo/handlebars-intl#55]
I was trying to use this library earlier with Ember CLI, but ran into some issues. One of the biggest limitations of this library right now is how all of the helper functions are stuck within `registerWith`.

For Ember, I need to be able to modify out `registerWith` to call `Ember.Handlebars.registerBoundHelper` rather than just `registerHelper`, or otherwise the data-binding won't cause a re-render when a model changes.

The best way for me to implement this would probably be for HandlebarsIntl to break out the helpers away from the `registerWith` function, and have them each be exported.  Then, it'd be a lot easier for me to import them and create a separate dist package just for Ember in a build step.

**Comment by ericf** [comment]
For Ember there's now Ember Intl:
http://formatjs.io/ember/

We could could move the helpers out as exports if we wanted to only support Handlebars 3.0, which removes the need the `instanceof` check on `SafeString` instances.

**Comment by gabel** [comment]
With webpack + handlebars-loader it won't work out either. The helper should be split into seperate modules.export to be included only if required.

**Comment by ericf** [comment]
> The helper should be split into seperate modules.export to be included only if required.

This is only possible now with Handlebars v3 and its improved `SafeString` support which now only needs to implement a `toHTML()` method.

But that said, it's not likely to be a high priority to refactor this package in that way. I also have no idea what Webpack + Handlebars-Loader even tries to do… but seems crazy that you wouldn't be able to call `HandlebarsIntl.register()` during some lifecycle event of the handlebars-loader.

**Comment by gabel** [comment]
Thanks for the feedback - i'll go with i18next and SafeString.
