### ISSUE TITLE
Global setup

### ISSUE THREAD

**Issue by yamsellem** [yahoo/handlebars-intl#57]
This may sound stupid, but I cannot find a proper answer in the docs.

Looking at [how translations are supposed to be given to templates](http://formatjs.io/guide/#structure-code), I've read this: 
> Setup one of FormatJS's integrations with the following data (the user's current locale, translated strings for that locale, optionally, any custom formats)

Looking to handlebars integration, I cannot figure out where I have to set the locale, translated strings and so on. In other words, where does `intlGet` find its lookup messages?

To be crystal clear: does `intlData` has a messages attribute? I don't find it in the source. And does the engine expects every template call to provide the locale, messages and so on? This seems tough.

Bonus question: when a message has no configuration — Welcome on board — is there a shortcut for the call `{{formatMessage (intlGet "messages.welcomeOnBoard")}}`? Thanks.

**Comment by caridy** [comment]
@yamsellem it is in the "render" tab on every example here: http://formatjs.io/handlebars/#formatMessage

you will see something like this:

```
var intlData = {
    "locales": "en-US",
    "messages": {
        "photos": "{name} took {numPhotos, plural,\n  =0 {no photos}\n  =1 {one photo}\n  other {# photos}\n} on {takenDate, date, long}.\n"
    }
};

var html = template(context, {
    data: {intl: intlData}
});
```

where `context` is:

```
var context = {
    name     : 'Annie',
    numPhotos: 1000,
    takenDate: Date.now()
};
```

**Comment by yamsellem** [comment]
Hi @caridy, thanks for your feedback.

I was talking about a global setup, something to avoid repeating the `intl` data all around the place.
For info, the `intl.messages`attributes is not shown a single time on the docs but it can be found in the github readme ;-). Maybe merging those two docs will help.

**Comment by juandopazo** [comment]
@yamsellem I'm pretty sure `intlGet` looks for the message in the Handlebars context.

**Comment by yamsellem** [comment]
@juandopazo if it does, that still implies providing the info every time, which is not realistic, don't you think?

**Comment by juandopazo** [comment]
Right. Caridy had answered correctly. I see your point now. In the server it's easy to add the messages in a centralized fashion, but it's not so clear how to do it in the client.

**Comment by yamsellem** [comment]
Cool, we're on the same page ;-).

Maybe someone else has an idea of how to do this client side, maybe it needs a patch?
Thanks again.

ps. by curiosity, how will you do this server side?

**Comment by caridy** [comment]
@yamsellem you call render once for the top level template, you pass the `data` object, which is propagated thru all partials, there is not need to pass that anywhere else, only when calling render on your top level template.

If you want to have more control on the message resolution process, you can simply ignore `getIntl` helper, and implement your own helper to locate your messages, there is nothing extraordinary about `getIntl`, it just returns a string.

**Comment by caridy** [comment]
as for the centralized messages, it is not recommended, especially if you're doing isomorphic apps since the resolution of messages happens per request on the server.

**Comment by ericf** [comment]
@yamsellem checkout the "RENDER" tab on this example:
http://formatjs.io/handlebars/#formatMessage

**Comment by yamsellem** [comment]
@ericf my bad, it is there — well hidden, but there ;-).
Still, the issue remains on client-side templating — a global configuration is a must have.
