### ISSUE TITLE
formatMessage with intlGet lookup fail on context sub properties

### ISSUE THREAD

**Issue by yamsellem** [yahoo/handlebars-intl#58]
It seems that using dot notation in `formatMessage`parameters won't work in combinaison with `intlGet`.

This works: `{{formatMessage "Welcome {name}" name=user.name}}`
This don't: `{{formatMessage (intlGet "messages.welcome") name=user.name}}`

Without the dot notation, both work.
This works: `{{formatMessage "Welcome {name}" name=name}}`
This too: `{{formatMessage (intlGet "messages.welcome") name=name}}`

**Comment by caridy** [comment]
this has nothing to do with handlebars-intl, this is handlebars, and the resolution process used by handlebars to resolve those props when passing it into a helper.
