### ISSUE TITLE
bower package

### ISSUE THREAD

**Issue by siddo420** [yahoo/handlebars-intl#71]
I cant find bower package.

Does that mean it can only be used on a Node.js server?

**Comment by jasonmit** [comment]
@siddo420 no, it works in the browser -- it's just not registered on bower. You can always pull it in over git if you choose to not use npm over bower.

`bower install git@github.com:yahoo/handlebars-intl.git`

**Comment by siddo420** [comment]
Thanks. I installed it using
```
bower install --save https://github.com/yahoo/handlebars-intl.git
```
Can you give an example of how to use it in Node? I have patched Node.js, installed relevant modules etc. But, I am not sure how to use it now.

I wanted to use it for error messages initially. For example, I have directory structure like below:
```
templates/en-US/errors/error1.hbs
templates/en-US/errors/error2.hbs
templates/fr-FR/errors/error1.hbs
templates/fr-FR/errors/error2.hbs
```
What is the best way to use them in my Node.js code? Also, can it be easily used with ConsolidateJS?

**Comment by jasonmit** [comment]
The documentation on the website covers the instructions: http://formatjs.io/handlebars/

**Comment by siddo420** [comment]
I had read that page already but it does not explain my particular case (I guess).

I couldn't easily use it with ConsolidateJS because I wanted to use pre-compiled handlebar templates. There is a way to get the handlebars object thru consolidate but it was throwing errors for some reason.

I managed to somehow make it work with lots of hacking :)
