### ISSUE TITLE
intlGet: Print message path if it is undefined

### ISSUE THREAD

**Issue by philmander** [yahoo/handlebars-intl#76]
I would like to change the behavior of the intlGet when a message path cannot be found.

Instead of throwing an error (https://github.com/yahoo/handlebars-intl/blob/master/src/helpers.js#L101), I would like to print just the message path. E.g.

``` html
<p>{{intlGet "messages.iamundefined"}}</p>
```

renders to:

```
<p>messages.iamundefined</p>
```

Is this a feature you would consider integrating? Maybe via an option to enable it or something?

**Comment by caridy** [comment]
IIRC we decided against this because it really hides trivial errors.
